# Étape 1 : build Angular
FROM node:20-alpine AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build --prod

# Étape 2 : nginx
FROM nginx:alpine
COPY --from=build /app/dist/frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
