

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ma_bdd
      - SPRING_DATASOURCE_USERNAME=monuser
      - SPRING_DATASOURCE_PASSWORD=monmdp
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ma_bdd
      POSTGRES_USER: monuser
      POSTGRES_PASSWORD: monmdp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
